### ISSUE TITLE
File pre-allocation fails

### ISSUE THREAD

**Issue by Beddhist** [alter3d/omdcct#3]
I have moved 2 plot files (419 GB each) off a SATA drive to make room to plot more. So, I know there is sufficient space.

When I try to plot 1600 nonces (4 GB) I get the error

File pre-allocation failed.
The *.plotting files are created with size 0.

Plotting 160 nonces works.

Linux Mint 32 bit, omdcct running sse core.

**Comment by samirsd** [comment]
happening to me too. any time i restart the plotter there is a failure and then my OS drive fills up
 "this computer has only 0 bytes disk space remaining" like what the hell?

**Comment by Kristian-Popov** [comment]
It is probably caused probably due to 32 bit OS.
`// 32 Bit and above 4GB?
	if( sizeof( void* ) < 8 ) {
		if( staggersize > 15000 ) {
			printf("Cant use stagger sizes above 15000 with 32-bit version\n");
			exit(-1);
		}
}`
It is too hard to work-around limitations on 32 bit platform in Burstcoin apps, I suggest to use 64 bit instead.

**Comment by Beddhist** [comment]
Ok, I understand. Thanks for your time.
